-d C:\Users\Valdir\Documents\Develop\fpga\tangPrime20k\spi_led_control\impl\gwsynthesis\spi_led_control.vg
-p GW2A-18-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\Valdir\Documents\Develop\fpga\tangPrime20k\spi_led_control\src\spi_led_control.cst
-cfg C:\Users\Valdir\Documents\Develop\fpga\tangPrime20k\spi_led_control\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
